### ISSUE TITLE
Using the Bluetooth interface

### ISSUE THREAD

**Issue by StudentofGermany** [seemoo-lab/pyshimmer#1]
Hey, 
I followed the instructions of the readme. I also patched LogAndStream Firmware on my Shimmer3 EXG.
Everything work till the example Program of the BT API. I am working on an Ubuntu 18.04.4 LTS.
I got the Error:
My name is: Shimmer_86A5
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/z-fcc/PycharmProjects/Test/pyshimmer/pyshimmer/bluetooth/bt_api.py", line 294, in _run_readloop
    self._bluetooth.process_single_input_event()
  File "/home/z-fcc/PycharmProjects/Test/pyshimmer/pyshimmer/bluetooth/bt_api.py", line 206, in process_single_input_event
    self._process_data_packet()
  File "/home/z-fcc/PycharmProjects/Test/pyshimmer/pyshimmer/bluetooth/bt_api.py", line 148, in _process_data_packet
    cb(packet)
  File "/home/z-fcc/PycharmProjects/Test/pyshimmer/test_hallo.py", line 26, in handler
    cur_value = pkt[EChannelType.INTERNAL_ADC_13]
  File "/home/z-fcc/PycharmProjects/Test/pyshimmer/pyshimmer/bluetooth/bt_commands.py", line 60, in __getitem__
    return self._values[item]
KeyError: <EChannelType.INTERNAL_ADC_13: 19>

After that i have to keyinterrupt the session:

Traceback (most recent call last):
  File "/home/z-fcc/PycharmProjects/Test/pyshimmer/test_hallo.py", line 43, in <module>
    shim_dev.stop_streaming()
  File "/home/z-fcc/PycharmProjects/Test/pyshimmer/pyshimmer/bluetooth/bt_api.py", line 480, in stop_streaming
    self._process_and_wait(StopStreamingCommand())
  File "/home/z-fcc/PycharmProjects/Test/pyshimmer/pyshimmer/bluetooth/bt_api.py", line 301, in _process_and_wait
    compl_obj.wait()
  File "/home/z-fcc/PycharmProjects/Test/pyshimmer/pyshimmer/bluetooth/bt_api.py", line 50, in wait
    self.__event.wait()
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

I can't find the mistake by my own. Can you help me pls? 

Dear StudentofGermany

**Comment by StudentofGermany** [comment]
Thx you very much! It helped me a lot. Now it works like it should :)
I close this now.
